containers/django/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

"""
accountsアプリのURL設定
"""

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", views.signup_view, name="signup"),
]

containers/django/book/urls.py
from django.urls import path
from . import views

"""
bookアプリケーションのURL設定を行うためのモジュール。

Attributes:
    app_name (str): アプリケーションの名前空間。
        この名前空間を利用して、URLの逆引きを行う。

    urlpatterns (list): URLのパターンのリスト。
        path関数を用いて、URLのパターンを追加する。
"""

urlpatterns = [
    path("", views.index_book_view, name="index"),
    path("filterby-user/<str:user>", views.index_book_view, name="filterby-user"),
    path("book/<int:pk>/", views.detail_book_view, name="detail-book"),
    path("book/create/", views.create_book_view, name="create-book"),
    path("book/<int:pk>/delete/", views.delete_book_view, name="delete-book"),
    path("book/<int:pk>/update/", views.update_book_view, name="update-book"),
    path("book/<int:book_id>/review/", views.create_review_view, name="review"),
]

containers/django/bookproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import os

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("book.urls")),
]

if os.environ.get("DEBUG") == "False":
    pass
elif os.environ.get("DJANGO_SETTINGS_MODULE") == "bookproject.local_settings":
    from . import local_settings as settings

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
elif os.environ.get("DJANGO_SETTINGS_MODULE") == "bookproject.docker_settings":
    from . import docker_settings as settings

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    raise ValueError("Unknown DJANGO_SETTINGS_MODULE")

containers/django/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    """
    DjangoのデフォルトのUserCreationFormを拡張するカスタムサインアップフォーム。

    Userモデルに基づいて新規ユーザーの作成を可能にするフォームで、
    ユーザー名のみをフィールドに含むシンプルなフォームです。

    Attributes:
    model: django.contrib.auth.models.User
        フォームが作成するモデルのインスタンス。
    fields: tuple
        フォームに表示されるフィールド。このフォームでは 'username' のみを使用。
    """

    class Meta:
        model = User
        fields = ("username",)

containers/django/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from .forms import SignupForm
from django.contrib import messages
from django.contrib.auth import login


def signup_view(request):
    """
    サインアップ（新規ユーザー登録）ページのビュー関数。

    POSTリクエストで受け取ったユーザー情報を検証し、有効であれば新しいユーザーアカウントを作成し、
    ユーザーをログイン状態にします。ユーザー作成が成功すると、'index'と名付けられたURLにリダイレクトされます。
    GETリクエストの場合は、空のサインアップフォームをユーザーに提示します。

    Parameters:
    request: HttpRequestオブジェクト
        ユーザーからのリクエスト情報を含むオブジェクト。

    Returns:
    HttpResponseオブジェクト
        サインアップフォームをレンダリングしたHTTPレスポンス、またはリダイレクトレスポンス。
    """
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "アカウントは正常に作成されました！")
            return redirect(reverse("index"))
    else:
        form = SignupForm()

    return render(request, "registration/signup.html", {"form": form})

containers/django/book/templates/book/book_create.html
{% extends "base.html" %}

{% block title %}プロダクト作成
{% endblock %}
{% block h1 %}書籍作成
{% endblock %}


{% block content %}
	<form method="POST" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">
		{% csrf_token %}
		{% for field in form %}
			<div class="mb-3">
				<label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
				{{ field }}
				{% if field.errors %}
					<div class="alert alert-danger">
						{{ field.errors|striptags }}
					</div>
				{% endif %}
			</div>
		{% endfor %}
		<input type="submit" value="作成する">
	</form>
{% endblock content %}

containers/django/book/templates/book/book_delete.html
{% extends "base.html" %}

{% block title %}プロダクト削除
{% endblock %}
{% block h1 %}書籍削除
{% endblock %}


{% block content %}
	<form method="POST">
		{% csrf_token %}
		<button type="submit">{{ object.title }}を削除する</button>
	</form>
{% endblock content %}

containers/django/book/templates/book/book_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	{{item.title}}
{% endblock %}
{% block h1 %}
	{{item.title}}
{% endblock %}

{% block content %}
	<!-- Bootstrapのグリッドシステム-->
	<br>
	<div class="album py-5 bg-light">

		<div
			class="container">
			<!-- 行を配置 -->
			<div
				class="row">
				<!-- 列の左右に余白offset-3を入れる-->
				<div class="col offset-0">
					<h2 class="card-title">
						{{item.title}}</h2>
					<h6>
						{% include "book/components/book_data.html" %}
					</h6>
					<div class="px-2">
						<span>
							{% if item.url %}
								<p>{{item.url|urlize}}</p>
							{% endif %}
						</span>
						<!-- コメント -->
						<p>{{item.text}}</p>

					</div>
					<br>
					<!-- 1枚目の写真 -->
					{% if item.thumbnail %}
						<p><img src="{{ item.thumbnail.url }}" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveaspectratio="xMidYMid slice" focusable="false">
						</p>
					</img>
				</p>
			{% else %}
				<p><img src="{% static 'book/noimage.png' %}" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveaspectratio="xMidYMid slice" focusable="false">
				</p>
			</img>
		</p>
	{% endif %}


	<a href="{% url 'review' item.pk %}" class="btn btn-primary">レビューする</a>
	<a href="{% url 'update-book' item.pk %}" class="btn btn-primary">編集する</a>
	<a href="{% url 'delete-book' item.pk %}" class="btn btn-primary">削除する</a>
	<span class="mb-2 small text-danger d-block text-start">編集と削除は投稿者の方のみご利用頂けます。</span>


	<br>
	{% if item.review_set.all %}
		<div class="border p-4 mb-2">
			{% for review in item.review_set.all %}
				<div>
					<h3 class="h4">{{review.title}}</h3>
					<div class="px-2">
						<span>(投稿ユーザー:
							{{review.user.username}})</span>
						<h6>評価:{{review.rate}}点</h6>
						<p>{{review.text}}</p>
					</div>
				</div>
			{% endfor %}
		</div>

	{% else %}
		<div class="border p-4 mb-2">
			<span class="mb-2 small d-block text-start">まだコメントはありません。</span>
		</div>


	{% endif %}


</div></div></div>{% endblock content %}

containers/django/book/templates/book/book_update.html
{% extends "base.html" %}

{% block title %}プロダクト修正
{% endblock %}
{% block h1 %}書籍修正
{% endblock %}

{% block content %}
	<form method="POST" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">
		{% csrf_token %}
		{% for field in form %}
			<div class="mb-3">
				<label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
				{{ field }}
				{% if field.errors %}
					<div class="alert alert-danger">
						{{ field.errors|striptags }}
					</div>
				{% endif %}
			</div>
		{% endfor %}
		<input type="submit" value="修正する">
	</form>
{% endblock content %}

containers/django/book/templates/book/components/catalog.html
{% load static %}

<!-- 列要素を配置 -->
<div class="col">
	<div class="card shadow-sm">
		<button
			type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'detail-book' item.pk %}'">
			<!-- svgタグをimgに変更src属性を追加して1枚目のイメージのURLを設定 -->
			{% if item.thumbnail %}
				<img src="{{ item.thumbnail.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveaspectratio="xMidYMid slice" focusable="false">
			{% else %}
				<img src="{% static 'book/noimage.png' %}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveaspectratio="xMidYMid slice" focusable="false">
			{% endif %}
			<title>Placeholder</title>
			<rect width="100%" height="100%" fill="#55595c"/>
		</button>


		<!-- タイトルとボタンを出力するブロック -->
		<div class="card-body">
			<p
				class="card-text">
				<!-- titleフィールドを出力 -->
				{{item.title}}
			</p>
			<div
				class="d-flex justify-content-end align-items-center">
				<!-- 投稿したユーザー名を出力-->
				<small class="text-muted">
					{% include "book/components/book_data.html" %}
				</small>
			</div>
		</div>
	</div>
	<!-- 列要素ここまで -->
</div>

containers/django/book/templates/book/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}ホーム
{% endblock %}
{% block h1 %}本だなアプリ
{% endblock %}

{% block content %}
	<!-- タイトルとナビゲーションボタン -->
	<section class="py-5 text-center container">
		<div class="row py-lg-5">
			<div
				class="col-lg-6 col-md-8 mx-auto">
				<!-- タイトルと本文 -->
				<h1 class="fw-light">Product Gallery</h1>
				<p class="lead text-muted">
					プロダクトの投稿サイトです。サムネイルも付けてくださいね！
				</p>
				<p>
					<!-- ナビゲーションボタン -->
					{% if request.user.is_authenticated %}
						<!-- ログイン中のボタン -->
						<a href="{% url 'create-book' %}" class="btn btn-primary my-2">プロダクト登録</a>
						<a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
					{% else %}
						<!-- ログイン状態ではない場合のボタン -->
						<a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">サインアップ</a>
						<a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">ログイン</a>
					{% endif %}
				</p>
				{% if messages %}
					<ul>
						{% for message in messages %}
							<p class="mb-1">
								{{ message }}
							</p>
						{% endfor %}
					</ul>
				{% endif %}
			</div>
		</div>
	</section>

	<div class="col-auto m-1">
		<select class="form-control select-custom" id="sample" onchange="viewChange();">
			<option value="select1">
				新しい順
			</option>
			<option value="select2">
				閲覧回数順
			</option>
			<option value="select3">
				レビュー評価順
			</option>
		</select>
	</div>

	<div
		class="album py-5 bg-light">

		<!-- Bootstrapのグリッドシステムを適用 -->
		<div
			class="container">

			<!-- 行要素を配置 -->
			<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" id="Box1">
				{% for item in index_book_list %}
					{% include "book/components/catalog.html" %}
				{% endfor %}
			</div>
			<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" id="Box2" style="display:none;">
				{% for item in index_book_list|dictsortreversed:"views" %}
					{% include "book/components/catalog.html" %}
				{% endfor %}
			</div>
			<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" id="Box3" style="display:none;">
				{% for item in review_ranking %}
					{% include "book/components/catalog.html" %}
				{% endfor %}
				<!-- 行要素ここまで -->
			</div>
			<!-- グリッドシステムここまで -->
		</div>
	</div>
	<link rel="stylesheet" href="{% static 'book/css/index.css' %}">
	<script src="{% static 'book/js/index.js' %}"></script>
{% endblock content %}

containers/django/book/templates/book/review_form.html
{% extends "base.html" %}

{% block title %}レビュー投稿
{% endblock %}
{% block h1 %}レビュー投稿
{% endblock %}

{% block content %}
	<form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
		{% csrf_token %}
		{% for field in form %}
			<div class="mb-3">
				<label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
				{{ field }}
				{% if field.errors %}
					<div class="alert alert-danger">
						{{ field.errors|striptags }}
					</div>
				{% endif %}
			</div>
		{% endfor %}
		<button type="submit" class="btn btn-success mt-4">投稿する</button>
	</form>
{% endblock content %}

containers/django/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
		<meta name="generator" content="Hugo 0.84.0">


		<title>
			{% block title %}{% endblock title %}| Product Gallery</title>
		<!-- staticでfavicon.icoのURLを生成する -->
		<link
		rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}">


		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

		<link rel="stylesheet" href="{% static 'book/css/base.css' %}">

	</head>

	<body>
		<!-- ページのヘッダー-->
		<header>
			<!-- ナビゲーションバーのヘッダー-->
			<div class="collapse bg-dark" id="navbarHeader">
				<div class="container">
					<div class="row">
						<div
							class="col-sm-8 col-md-7 py-4">
							<!-- ヘッダーのタイトルと本文-->
							<h4 class="text-white">お気に入りを見つけよう！</h4>
							<p class="text-muted">
								誰でも参加できるプロダクト投稿サイトです。
								<br>
								自分で制作したプロダクトなら何でもオッケー！
								                            コメントも付けてみてください！
							</p>
						</div>
						<div class="col-sm-4 offset-md-1 py-4">
							<h4 class="text-white">Menu</h4>
							<ul
								class="list-unstyled">
								<!-- ナビゲーションメニュー-->
								{% if request.user.is_authenticated %}
									<!-- ログイン中のメニュー-->
									<li>
										<a href="{% url 'index' %}" class="text-white">プロダクト一覧</a>
									</li>
									<li>
										<a href="{% url 'create-book' %}" class="text-white">プロダクト登録</a>
									</li>
									<li>
										<a href="{% url 'accounts:logout' %}" class="text-white">ログアウト</a>
									</li>
								{% else %}
									<!-- ログイン状態ではない場合のメニュー-->
									<li>
										<a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a>
									</li>
									<li>
										<a href="{% url 'accounts:login' %}" class="text-white">ログイン</a>
									</li>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!-- ナビゲーションバー-->
			<div class="navbar navbar-dark bg-dark shadow-sm">
				<div
					class="container">
					<!-- トップページへのリンク-->
					<a href="{% url 'index' %}" class="navbar-brand d-flex align-items-center">
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewbox="0 0 24 24">
							<path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
							<circle cx="12" cy="13" r="4"/>
						</svg>
						<!-- リンクテキスト-->
						<strong>
							Product Gallery
							<small class="text-muted">
								&nbsp;&nbsp;by yotech<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevrons-right" width="16" height="16" viewbox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
									<path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
									<path d="M7 7l5 5l-5 5"></path>
									<path d="M13 7l5 5l-5 5"></path>
								</svg>
							</small>
						</strong>
					</a>
					<!-- トグルボタン-->
					<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
				</div>
			</div>
		</header>

		<!-- メインコンテンツ-->
		<main>
			<!-- <main>タグの要素をすべて削除して以下に書き換え-->
			<!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む-->{% block content %}
		{% endblock content %}
		</main>

		<!-- フッター -->
			<footer class="text-muted py-5"> <div class="container">
				<p class="float-end mb-1">
					<a href="#">Back to top</a>
				</p>
				<!-- フッターのテキストを任意のものに書き換え-->
				<p class="mb-1">
					Product Gallery is &copy; Bootstrap, but please post a lot!</p>
			</div>
		</footer>

		<!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け-->
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

	</body>

</html>